// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnnouncementBar from './components/AnnouncementBar';
import Navbar from "./components/Navbar"; 
import Footer from "./components/Footer"; // ✅ Import your Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          display: 'flex', // Enable flexbox for the entire page
          flexDirection: 'column', // Stack elements vertically
          minHeight: '100vh', // Ensure the body takes full viewport height
        }}
      >
        <AnnouncementBar />
        <Navbar />
        <main
          style={{
            flex: 1, // Allow the main content to take up all available space
          }}
        >
          {children}
        </main>
        <Footer /> {/* This will stay at the bottom */}
      </body>
    </html>
  );
}
